name: Build
on:
  [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13

    - name: Check out code
      uses: actions/checkout@v1
      with:
        submodules: true
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Move bosh-cli submodule to GOPATH/src
      run: |
        mkdir -p $(go env GOPATH)/src/github.com/cloudfoundry
        mv $GITHUB_WORKSPACE/bosh-cli $(go env GOPATH)/src/github.com/cloudfoundry/

    - name: Add patch, and Build
      run: |
        cd $(go env GOPATH)/src/github.com/cloudfoundry/bosh-cli
        patch -l -p1  < $GITHUB_WORKSPACE/patch.txt
        bin/build
